//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCED040VM_ThongTinHLV : BaseViewModel
	{

		private ICommand _editHLVInfoCommand;

		public ICommand EditHLVInfoCommand
		{
			get
			{
				if (_editHLVInfoCommand == null)
				{
					_editHLVInfoCommand = new RelayCommand(ExecuteEditHLVInfoCommand);
				}
				return _editHLVInfoCommand;
			}
		}

		private ICommand _saveHLVInfoCommand;

		public ICommand SaveHLVInfoCommand
		{
			get
			{
				if (_saveHLVInfoCommand == null)
				{
					_saveHLVInfoCommand = 
						new RelayCommand(ExecuteSaveHLVInfoCommand, CanExecuteSaveHLVInfoCommand);
				}
				return _saveHLVInfoCommand;
			}
		}

		private ICommand _deleteHLVInfoCommand;

		public ICommand DeleteHLVInfoCommand
		{
			get
			{
				if (_deleteHLVInfoCommand == null)
				{
					_deleteHLVInfoCommand = new RelayCommand(ExecuteDeleteHLVInfoCommand);
				}
				return _deleteHLVInfoCommand;
			}
		}

	}
}



