//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCED010VM_Nguoidung : BaseViewModel
	{

		private ICommand _getListNguoiDungCommand;

		public ICommand GetListNguoiDungCommand
		{
			get
			{
				if (_getListNguoiDungCommand == null)
				{
					_getListNguoiDungCommand = new RelayCommand(ExecuteGetListNguoiDungCommand);
				}
				return _getListNguoiDungCommand;
			}
		}

		private ICommand _nguoiDungChangeCommand;

		public ICommand NguoiDungChangeCommand
		{
			get
			{
				if (_nguoiDungChangeCommand == null)
				{
					_nguoiDungChangeCommand = new RelayCommand(ExecuteNguoiDungChangeCommand);
				}
				return _nguoiDungChangeCommand;
			}
		}

		private ICommand _getListLoaiNVCommand;

		public ICommand GetListLoaiNVCommand
		{
			get
			{
				if (_getListLoaiNVCommand == null)
				{
					_getListLoaiNVCommand = new RelayCommand(ExecuteGetListLoaiNVCommand);
				}
				return _getListLoaiNVCommand;
			}
		}

		private ICommand _logoutCommand;

		public ICommand LogoutCommand
		{
			get
			{
				if (_logoutCommand == null)
				{
					_logoutCommand = new RelayCommand(ExecuteLogoutCommand);
				}
				return _logoutCommand;
			}
		}

		private ICommand _openAddNguoiDungCommand;

		public ICommand OpenAddNguoiDungCommand
		{
			get
			{
				if (_openAddNguoiDungCommand == null)
				{
					_openAddNguoiDungCommand = 
						new RelayCommand(ExecuteOpenAddNguoiDungCommand, CanExecuteOpenAddNguoiDungCommand);
				}
				return _openAddNguoiDungCommand;
			}
		}

		private ICommand _updateNguoiDungCommand;

		public ICommand UpdateNguoiDungCommand
		{
			get
			{
				if (_updateNguoiDungCommand == null)
				{
					_updateNguoiDungCommand = 
						new RelayCommand(ExecuteUpdateNguoiDungCommand, CanExecuteUpdateNguoiDungCommand);
				}
				return _updateNguoiDungCommand;
			}
		}

		private ICommand _cancelUpdateNguoiDungCommand;

		public ICommand CancelUpdateNguoiDungCommand
		{
			get
			{
				if (_cancelUpdateNguoiDungCommand == null)
				{
					_cancelUpdateNguoiDungCommand = new RelayCommand(ExecuteCancelUpdateNguoiDungCommand);
				}
				return _cancelUpdateNguoiDungCommand;
			}
		}

		private ICommand _deleteNguoiDungCommand;

		public ICommand DeleteNguoiDungCommand
		{
			get
			{
				if (_deleteNguoiDungCommand == null)
				{
					_deleteNguoiDungCommand = 
						new RelayCommand(ExecuteDeleteNguoiDungCommand, CanExecuteDeleteNguoiDungCommand);
				}
				return _deleteNguoiDungCommand;
			}
		}

	}
}



