//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCED020VM_SwitchThongTinDangKy : BaseViewModel
	{

		private ICommand _nextCommand;

		public ICommand NextCommand
		{
			get
			{
				if (_nextCommand == null)
				{
					_nextCommand = 
						new RelayCommand(ExecuteNextCommand, CanExecuteNextCommand);
				}
				return _nextCommand;
			}
		}

		private ICommand _backCommand;

		public ICommand BackCommand
		{
			get
			{
				if (_backCommand == null)
				{
					_backCommand = new RelayCommand(ExecuteBackCommand);
				}
				return _backCommand;
			}
		}

		private ICommand _closeWindowCommand;

		public ICommand CloseWindowCommand
		{
			get
			{
				if (_closeWindowCommand == null)
				{
					_closeWindowCommand = new RelayCommand(ExecuteCloseWindowCommand);
				}
				return _closeWindowCommand;
			}
		}

	}
}



