//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCED070VM_ThongTinTrongTai : BaseViewModel
	{

		private ICommand _editTrongTaiInfoCommand;

		public ICommand EditTrongTaiInfoCommand
		{
			get
			{
				if (_editTrongTaiInfoCommand == null)
				{
					_editTrongTaiInfoCommand = new RelayCommand(ExecuteEditTrongTaiInfoCommand);
				}
				return _editTrongTaiInfoCommand;
			}
		}

		private ICommand _saveTrongTaiInfoCommand;

		public ICommand SaveTrongTaiInfoCommand
		{
			get
			{
				if (_saveTrongTaiInfoCommand == null)
				{
					_saveTrongTaiInfoCommand = 
						new RelayCommand(ExecuteSaveTrongTaiInfoCommand, CanExecuteSaveTrongTaiInfoCommand);
				}
				return _saveTrongTaiInfoCommand;
			}
		}

		private ICommand _deleteTrongTaiInfoCommand;

		public ICommand DeleteTrongTaiInfoCommand
		{
			get
			{
				if (_deleteTrongTaiInfoCommand == null)
				{
					_deleteTrongTaiInfoCommand = new RelayCommand(ExecuteDeleteTrongTaiInfoCommand);
				}
				return _deleteTrongTaiInfoCommand;
			}
		}

	}
}



