//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCED050VM_ThongTinSVD : BaseViewModel
	{

		private ICommand _editSVDInfoCommand;

		public ICommand EditSVDInfoCommand
		{
			get
			{
				if (_editSVDInfoCommand == null)
				{
					_editSVDInfoCommand = new RelayCommand(ExecuteEditSVDInfoCommand);
				}
				return _editSVDInfoCommand;
			}
		}

		private ICommand _saveSVDInfoCommand;

		public ICommand SaveSVDInfoCommand
		{
			get
			{
				if (_saveSVDInfoCommand == null)
				{
					_saveSVDInfoCommand = 
						new RelayCommand(ExecuteSaveSVDInfoCommand, CanExecuteSaveSVDInfoCommand);
				}
				return _saveSVDInfoCommand;
			}
		}

		private ICommand _deleteSVDInfoCommand;

		public ICommand DeleteSVDInfoCommand
		{
			get
			{
				if (_deleteSVDInfoCommand == null)
				{
					_deleteSVDInfoCommand = new RelayCommand(ExecuteDeleteSVDInfoCommand);
				}
				return _deleteSVDInfoCommand;
			}
		}

	}
}



