//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCLG011VM_DoiMatKhau : BaseViewModel
	{

		private ICommand _saveCommand;

		public ICommand SaveCommand
		{
			get
			{
				if (_saveCommand == null)
				{
					_saveCommand = 
						new RelayCommand(ExecuteSaveCommand, CanExecuteSaveCommand);
				}
				return _saveCommand;
			}
		}

		private ICommand _cancelCommand;

		public ICommand CancelCommand
		{
			get
			{
				if (_cancelCommand == null)
				{
					_cancelCommand = new RelayCommand(ExecuteCancelCommand);
				}
				return _cancelCommand;
			}
		}

	}
}



