//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCMN010VM_MainWindow : BaseViewModel
	{

		private ICommand _logoutCommand;

		public ICommand LogoutCommand
		{
			get
			{
				if (_logoutCommand == null)
				{
					_logoutCommand = new RelayCommand(ExecuteLogoutCommand);
				}
				return _logoutCommand;
			}
		}

		private ICommand _cancelCommand;

		public ICommand CancelCommand
		{
			get
			{
				if (_cancelCommand == null)
				{
					_cancelCommand = new RelayCommand(ExecuteCancelCommand);
				}
				return _cancelCommand;
			}
		}

		private ICommand _menuTabChangeCommand;

		public ICommand MenuTabChangeCommand
		{
			get
			{
				if (_menuTabChangeCommand == null)
				{
					_menuTabChangeCommand = new RelayCommand(ExecuteMenuTabChangeCommand);
				}
				return _menuTabChangeCommand;
			}
		}

	}
}



