//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC030VM_DanhSachCauThu : BaseViewModel
	{

		private ICommand _cauThuChangedCommand;

		public ICommand CauThuChangedCommand
		{
			get
			{
				if (_cauThuChangedCommand == null)
				{
					_cauThuChangedCommand = new RelayCommand(ExecuteCauThuChangedCommand);
				}
				return _cauThuChangedCommand;
			}
		}

		private ICommand _openAddCauThuCommand;

		public ICommand OpenAddCauThuCommand
		{
			get
			{
				if (_openAddCauThuCommand == null)
				{
					_openAddCauThuCommand = new RelayCommand(ExecuteOpenAddCauThuCommand);
				}
				return _openAddCauThuCommand;
			}
		}

		private ICommand _deleteCauThuCommand;

		public ICommand DeleteCauThuCommand
		{
			get
			{
				if (_deleteCauThuCommand == null)
				{
					_deleteCauThuCommand = 
						new RelayCommand(ExecuteDeleteCauThuCommand, CanExecuteDeleteCauThuCommand);
				}
				return _deleteCauThuCommand;
			}
		}

		private ICommand _openEditCauThuCommand;

		public ICommand OpenEditCauThuCommand
		{
			get
			{
				if (_openEditCauThuCommand == null)
				{
					_openEditCauThuCommand = 
						new RelayCommand(ExecuteOpenEditCauThuCommand, CanExecuteOpenEditCauThuCommand);
				}
				return _openEditCauThuCommand;
			}
		}

		private ICommand _confirmChangeCauThuCommand;

		public ICommand ConfirmChangeCauThuCommand
		{
			get
			{
				if (_confirmChangeCauThuCommand == null)
				{
					_confirmChangeCauThuCommand = 
						new RelayCommand(ExecuteConfirmChangeCauThuCommand, CanExecuteConfirmChangeCauThuCommand);
				}
				return _confirmChangeCauThuCommand;
			}
		}

		private ICommand _cancelCauThuCommand;

		public ICommand CancelCauThuCommand
		{
			get
			{
				if (_cancelCauThuCommand == null)
				{
					_cancelCauThuCommand = 
						new RelayCommand(ExecuteCancelCauThuCommand, CanExecuteCancelCauThuCommand);
				}
				return _cancelCauThuCommand;
			}
		}

		private ICommand _searchCauThuCommand;

		public ICommand SearchCauThuCommand
		{
			get
			{
				if (_searchCauThuCommand == null)
				{
					_searchCauThuCommand = 
						new RelayCommand(ExecuteSearchCauThuCommand, CanExecuteSearchCauThuCommand);
				}
				return _searchCauThuCommand;
			}
		}

		private ICommand _searchAllCommand;

		public ICommand SearchAllCommand
		{
			get
			{
				if (_searchAllCommand == null)
				{
					_searchAllCommand = new RelayCommand(ExecuteSearchAllCommand);
				}
				return _searchAllCommand;
			}
		}

		private ICommand _chooseAvaCommand;

		public ICommand ChooseAvaCommand
		{
			get
			{
				if (_chooseAvaCommand == null)
				{
					_chooseAvaCommand = 
						new RelayCommand(ExecuteChooseAvaCommand, CanExecuteChooseAvaCommand);
				}
				return _chooseAvaCommand;
			}
		}

	}
}



