//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC020VM_DanhSachChung : BaseViewModel
	{

		private ICommand _getInfoHLVCommand;

		public ICommand GetInfoHLVCommand
		{
			get
			{
				if (_getInfoHLVCommand == null)
				{
					_getInfoHLVCommand = 
						new RelayCommand(ExecuteGetInfoHLVCommand, CanExecuteGetInfoHLVCommand);
				}
				return _getInfoHLVCommand;
			}
		}

		private ICommand _getInfoSVDCommand;

		public ICommand GetInfoSVDCommand
		{
			get
			{
				if (_getInfoSVDCommand == null)
				{
					_getInfoSVDCommand = 
						new RelayCommand(ExecuteGetInfoSVDCommand, CanExecuteGetInfoSVDCommand);
				}
				return _getInfoSVDCommand;
			}
		}

		private ICommand _getInfoTrongTaiCommand;

		public ICommand GetInfoTrongTaiCommand
		{
			get
			{
				if (_getInfoTrongTaiCommand == null)
				{
					_getInfoTrongTaiCommand = 
						new RelayCommand(ExecuteGetInfoTrongTaiCommand, CanExecuteGetInfoTrongTaiCommand);
				}
				return _getInfoTrongTaiCommand;
			}
		}

		private ICommand _getInfoThePhatCommand;

		public ICommand GetInfoThePhatCommand
		{
			get
			{
				if (_getInfoThePhatCommand == null)
				{
					_getInfoThePhatCommand = 
						new RelayCommand(ExecuteGetInfoThePhatCommand, CanExecuteGetInfoThePhatCommand);
				}
				return _getInfoThePhatCommand;
			}
		}

		private ICommand _getReportBanThangCommand;

		public ICommand GetReportBanThangCommand
		{
			get
			{
				if (_getReportBanThangCommand == null)
				{
					_getReportBanThangCommand = new RelayCommand(ExecuteGetReportBanThangCommand);
				}
				return _getReportBanThangCommand;
			}
		}

		private ICommand _addHLVCommand;

		public ICommand AddHLVCommand
		{
			get
			{
				if (_addHLVCommand == null)
				{
					_addHLVCommand = new RelayCommand(ExecuteAddHLVCommand);
				}
				return _addHLVCommand;
			}
		}

		private ICommand _addSVDCommand;

		public ICommand AddSVDCommand
		{
			get
			{
				if (_addSVDCommand == null)
				{
					_addSVDCommand = new RelayCommand(ExecuteAddSVDCommand);
				}
				return _addSVDCommand;
			}
		}

		private ICommand _addTrongTaiCommand;

		public ICommand AddTrongTaiCommand
		{
			get
			{
				if (_addTrongTaiCommand == null)
				{
					_addTrongTaiCommand = new RelayCommand(ExecuteAddTrongTaiCommand);
				}
				return _addTrongTaiCommand;
			}
		}

		private ICommand _getListHLVCommand;

		public ICommand GetListHLVCommand
		{
			get
			{
				if (_getListHLVCommand == null)
				{
					_getListHLVCommand = new RelayCommand(ExecuteGetListHLVCommand);
				}
				return _getListHLVCommand;
			}
		}

		private ICommand _getListSVDCommand;

		public ICommand GetListSVDCommand
		{
			get
			{
				if (_getListSVDCommand == null)
				{
					_getListSVDCommand = new RelayCommand(ExecuteGetListSVDCommand);
				}
				return _getListSVDCommand;
			}
		}

		private ICommand _getListTrongTaiCommand;

		public ICommand GetListTrongTaiCommand
		{
			get
			{
				if (_getListTrongTaiCommand == null)
				{
					_getListTrongTaiCommand = new RelayCommand(ExecuteGetListTrongTaiCommand);
				}
				return _getListTrongTaiCommand;
			}
		}

		private ICommand _getListThePhatCommand;

		public ICommand GetListThePhatCommand
		{
			get
			{
				if (_getListThePhatCommand == null)
				{
					_getListThePhatCommand = new RelayCommand(ExecuteGetListThePhatCommand);
				}
				return _getListThePhatCommand;
			}
		}

		private ICommand _getListBanThangCommand;

		public ICommand GetListBanThangCommand
		{
			get
			{
				if (_getListBanThangCommand == null)
				{
					_getListBanThangCommand = new RelayCommand(ExecuteGetListBanThangCommand);
				}
				return _getListBanThangCommand;
			}
		}

	}
}



