//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC060VM_Thongtin : BaseViewModel
	{

		private ICommand _getLichDaCommand;

		public ICommand GetLichDaCommand
		{
			get
			{
				if (_getLichDaCommand == null)
				{
					_getLichDaCommand = new RelayCommand(ExecuteGetLichDaCommand);
				}
				return _getLichDaCommand;
			}
		}

		private ICommand _openLichDauChiTietCommand;

		public ICommand OpenLichDauChiTietCommand
		{
			get
			{
				if (_openLichDauChiTietCommand == null)
				{
					_openLichDauChiTietCommand = new RelayCommand(ExecuteOpenLichDauChiTietCommand);
				}
				return _openLichDauChiTietCommand;
			}
		}

		private ICommand _openDsCauThuCommand;

		public ICommand OpenDsCauThuCommand
		{
			get
			{
				if (_openDsCauThuCommand == null)
				{
					_openDsCauThuCommand = new RelayCommand(ExecuteOpenDsCauThuCommand);
				}
				return _openDsCauThuCommand;
			}
		}

		private ICommand _getBangXHCommand;

		public ICommand GetBangXHCommand
		{
			get
			{
				if (_getBangXHCommand == null)
				{
					_getBangXHCommand = new RelayCommand(ExecuteGetBangXHCommand);
				}
				return _getBangXHCommand;
			}
		}

		private ICommand _logoutCommand;

		public ICommand LogoutCommand
		{
			get
			{
				if (_logoutCommand == null)
				{
					_logoutCommand = new RelayCommand(ExecuteLogoutCommand);
				}
				return _logoutCommand;
			}
		}

		private ICommand _openDangKiDoiBongCommand;

		public ICommand OpenDangKiDoiBongCommand
		{
			get
			{
				if (_openDangKiDoiBongCommand == null)
				{
					_openDangKiDoiBongCommand = new RelayCommand(ExecuteOpenDangKiDoiBongCommand);
				}
				return _openDangKiDoiBongCommand;
			}
		}

		private ICommand _openChiTietDoiBongCommand;

		public ICommand OpenChiTietDoiBongCommand
		{
			get
			{
				if (_openChiTietDoiBongCommand == null)
				{
					_openChiTietDoiBongCommand = 
						new RelayCommand(ExecuteOpenChiTietDoiBongCommand, CanExecuteOpenChiTietDoiBongCommand);
				}
				return _openChiTietDoiBongCommand;
			}
		}

		private ICommand _xoaDoiBongCommand;

		public ICommand XoaDoiBongCommand
		{
			get
			{
				if (_xoaDoiBongCommand == null)
				{
					_xoaDoiBongCommand = 
						new RelayCommand(ExecuteXoaDoiBongCommand, CanExecuteXoaDoiBongCommand);
				}
				return _xoaDoiBongCommand;
			}
		}

		private ICommand _openReportCommand;

		public ICommand OpenReportCommand
		{
			get
			{
				if (_openReportCommand == null)
				{
					_openReportCommand = new RelayCommand(ExecuteOpenReportCommand);
				}
				return _openReportCommand;
			}
		}

		private ICommand _capNhatBXHCommand;

		public ICommand CapNhatBXHCommand
		{
			get
			{
				if (_capNhatBXHCommand == null)
				{
					_capNhatBXHCommand = new RelayCommand(ExecuteCapNhatBXHCommand);
				}
				return _capNhatBXHCommand;
			}
		}

	}
}



