//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC050VM_LichThiDau : BaseViewModel
	{

		private ICommand _taoLichDauCommand;

		public ICommand TaoLichDauCommand
		{
			get
			{
				if (_taoLichDauCommand == null)
				{
					_taoLichDauCommand = new RelayCommand(ExecuteTaoLichDauCommand);
				}
				return _taoLichDauCommand;
			}
		}

		private ICommand _editTranDauCommand;

		public ICommand EditTranDauCommand
		{
			get
			{
				if (_editTranDauCommand == null)
				{
					_editTranDauCommand = 
						new RelayCommand(ExecuteEditTranDauCommand, CanExecuteEditTranDauCommand);
				}
				return _editTranDauCommand;
			}
		}

		private ICommand _ketQuaTranDauCommand;

		public ICommand KetQuaTranDauCommand
		{
			get
			{
				if (_ketQuaTranDauCommand == null)
				{
					_ketQuaTranDauCommand = 
						new RelayCommand(ExecuteKetQuaTranDauCommand, CanExecuteKetQuaTranDauCommand);
				}
				return _ketQuaTranDauCommand;
			}
		}

		private ICommand _saveTranDauCommand;

		public ICommand SaveTranDauCommand
		{
			get
			{
				if (_saveTranDauCommand == null)
				{
					_saveTranDauCommand = 
						new RelayCommand(ExecuteSaveTranDauCommand, CanExecuteSaveTranDauCommand);
				}
				return _saveTranDauCommand;
			}
		}

		private ICommand _cancelEditTrandauCommand;

		public ICommand CancelEditTrandauCommand
		{
			get
			{
				if (_cancelEditTrandauCommand == null)
				{
					_cancelEditTrandauCommand = 
						new RelayCommand(ExecuteCancelEditTrandauCommand, CanExecuteCancelEditTrandauCommand);
				}
				return _cancelEditTrandauCommand;
			}
		}

		private ICommand _selectTranDauCommand;

		public ICommand SelectTranDauCommand
		{
			get
			{
				if (_selectTranDauCommand == null)
				{
					_selectTranDauCommand = new RelayCommand(ExecuteSelectTranDauCommand);
				}
				return _selectTranDauCommand;
			}
		}

	}
}



