//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC080VM_QuyDinh : BaseViewModel
	{

		private ICommand _loadQuyDinhCommand;

		public ICommand LoadQuyDinhCommand
		{
			get
			{
				if (_loadQuyDinhCommand == null)
				{
					_loadQuyDinhCommand = new RelayCommand(ExecuteLoadQuyDinhCommand);
				}
				return _loadQuyDinhCommand;
			}
		}

		private ICommand _loadLoaiBanThangCommand;

		public ICommand LoadLoaiBanThangCommand
		{
			get
			{
				if (_loadLoaiBanThangCommand == null)
				{
					_loadLoaiBanThangCommand = new RelayCommand(ExecuteLoadLoaiBanThangCommand);
				}
				return _loadLoaiBanThangCommand;
			}
		}

		private ICommand _logoutCommand;

		public ICommand LogoutCommand
		{
			get
			{
				if (_logoutCommand == null)
				{
					_logoutCommand = new RelayCommand(ExecuteLogoutCommand);
				}
				return _logoutCommand;
			}
		}

		private ICommand _updateQuyDinh1Command;

		public ICommand UpdateQuyDinh1Command
		{
			get
			{
				if (_updateQuyDinh1Command == null)
				{
					_updateQuyDinh1Command = new RelayCommand(ExecuteUpdateQuyDinh1Command);
				}
				return _updateQuyDinh1Command;
			}
		}

		private ICommand _cancelUpdateQuyDinh1Command;

		public ICommand CancelUpdateQuyDinh1Command
		{
			get
			{
				if (_cancelUpdateQuyDinh1Command == null)
				{
					_cancelUpdateQuyDinh1Command = 
						new RelayCommand(ExecuteCancelUpdateQuyDinh1Command, CanExecuteCancelUpdateQuyDinh1Command);
				}
				return _cancelUpdateQuyDinh1Command;
			}
		}

		private ICommand _updateQuyDinh3Command;

		public ICommand UpdateQuyDinh3Command
		{
			get
			{
				if (_updateQuyDinh3Command == null)
				{
					_updateQuyDinh3Command = new RelayCommand(ExecuteUpdateQuyDinh3Command);
				}
				return _updateQuyDinh3Command;
			}
		}

		private ICommand _cancelUpdateQuyDinh3Command;

		public ICommand CancelUpdateQuyDinh3Command
		{
			get
			{
				if (_cancelUpdateQuyDinh3Command == null)
				{
					_cancelUpdateQuyDinh3Command = 
						new RelayCommand(ExecuteCancelUpdateQuyDinh3Command, CanExecuteCancelUpdateQuyDinh3Command);
				}
				return _cancelUpdateQuyDinh3Command;
			}
		}

		private ICommand _updateQuyDinh4Command;

		public ICommand UpdateQuyDinh4Command
		{
			get
			{
				if (_updateQuyDinh4Command == null)
				{
					_updateQuyDinh4Command = new RelayCommand(ExecuteUpdateQuyDinh4Command);
				}
				return _updateQuyDinh4Command;
			}
		}

		private ICommand _cancelUpdateQuyDinh4Command;

		public ICommand CancelUpdateQuyDinh4Command
		{
			get
			{
				if (_cancelUpdateQuyDinh4Command == null)
				{
					_cancelUpdateQuyDinh4Command = 
						new RelayCommand(ExecuteCancelUpdateQuyDinh4Command, CanExecuteCancelUpdateQuyDinh4Command);
				}
				return _cancelUpdateQuyDinh4Command;
			}
		}

		private ICommand _addLoaiBTCommand;

		public ICommand AddLoaiBTCommand
		{
			get
			{
				if (_addLoaiBTCommand == null)
				{
					_addLoaiBTCommand = new RelayCommand(ExecuteAddLoaiBTCommand);
				}
				return _addLoaiBTCommand;
			}
		}

		private ICommand _deleteLoaiBTCommand;

		public ICommand DeleteLoaiBTCommand
		{
			get
			{
				if (_deleteLoaiBTCommand == null)
				{
					_deleteLoaiBTCommand = 
						new RelayCommand(ExecuteDeleteLoaiBTCommand, CanExecuteDeleteLoaiBTCommand);
				}
				return _deleteLoaiBTCommand;
			}
		}

		private ICommand _updateLoaiBTCommand;

		public ICommand UpdateLoaiBTCommand
		{
			get
			{
				if (_updateLoaiBTCommand == null)
				{
					_updateLoaiBTCommand = 
						new RelayCommand(ExecuteUpdateLoaiBTCommand, CanExecuteUpdateLoaiBTCommand);
				}
				return _updateLoaiBTCommand;
			}
		}

		private ICommand _cancelUpdateLoaiBTCommand;

		public ICommand CancelUpdateLoaiBTCommand
		{
			get
			{
				if (_cancelUpdateLoaiBTCommand == null)
				{
					_cancelUpdateLoaiBTCommand = new RelayCommand(ExecuteCancelUpdateLoaiBTCommand);
				}
				return _cancelUpdateLoaiBTCommand;
			}
		}

	}
}



