//------------------------------------------------------------------------------
// <auto-generated>
//     text template column for binding
//
//     Auto refresh
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using Microsoft.TeamFoundation.MVVM;
using QuanLyGiaiBongDa.Common;
using QuanLyGiaiBongDa.ViewModels;
namespace QuanLyGiaiBongDa.ViewModels
{

	partial class SCRC051VM_KetQuaTranDau : BaseViewModel
	{

		private ICommand _openUpdateKetQuaCommand;

		public ICommand OpenUpdateKetQuaCommand
		{
			get
			{
				if (_openUpdateKetQuaCommand == null)
				{
					_openUpdateKetQuaCommand = new RelayCommand(ExecuteOpenUpdateKetQuaCommand);
				}
				return _openUpdateKetQuaCommand;
			}
		}

		private ICommand _updateKetQuaCommand;

		public ICommand UpdateKetQuaCommand
		{
			get
			{
				if (_updateKetQuaCommand == null)
				{
					_updateKetQuaCommand = 
						new RelayCommand(ExecuteUpdateKetQuaCommand, CanExecuteUpdateKetQuaCommand);
				}
				return _updateKetQuaCommand;
			}
		}

		private ICommand _cancelUpdateCommand;

		public ICommand CancelUpdateCommand
		{
			get
			{
				if (_cancelUpdateCommand == null)
				{
					_cancelUpdateCommand = 
						new RelayCommand(ExecuteCancelUpdateCommand, CanExecuteCancelUpdateCommand);
				}
				return _cancelUpdateCommand;
			}
		}

		private ICommand _addBanThangCommand;

		public ICommand AddBanThangCommand
		{
			get
			{
				if (_addBanThangCommand == null)
				{
					_addBanThangCommand = 
						new RelayCommand(ExecuteAddBanThangCommand, CanExecuteAddBanThangCommand);
				}
				return _addBanThangCommand;
			}
		}

		private ICommand _deleteBanThangCommand;

		public ICommand DeleteBanThangCommand
		{
			get
			{
				if (_deleteBanThangCommand == null)
				{
					_deleteBanThangCommand = 
						new RelayCommand(ExecuteDeleteBanThangCommand, CanExecuteDeleteBanThangCommand);
				}
				return _deleteBanThangCommand;
			}
		}

		private ICommand _confirmAddBanThangCommand;

		public ICommand ConfirmAddBanThangCommand
		{
			get
			{
				if (_confirmAddBanThangCommand == null)
				{
					_confirmAddBanThangCommand = 
						new RelayCommand(ExecuteConfirmAddBanThangCommand, CanExecuteConfirmAddBanThangCommand);
				}
				return _confirmAddBanThangCommand;
			}
		}

		private ICommand _cancelAddBanThangCommand;

		public ICommand CancelAddBanThangCommand
		{
			get
			{
				if (_cancelAddBanThangCommand == null)
				{
					_cancelAddBanThangCommand = new RelayCommand(ExecuteCancelAddBanThangCommand);
				}
				return _cancelAddBanThangCommand;
			}
		}

		private ICommand _changeDoiBongCommand;

		public ICommand ChangeDoiBongCommand
		{
			get
			{
				if (_changeDoiBongCommand == null)
				{
					_changeDoiBongCommand = new RelayCommand(ExecuteChangeDoiBongCommand);
				}
				return _changeDoiBongCommand;
			}
		}

		private ICommand _openThePhatCommand;

		public ICommand OpenThePhatCommand
		{
			get
			{
				if (_openThePhatCommand == null)
				{
					_openThePhatCommand = new RelayCommand(ExecuteOpenThePhatCommand);
				}
				return _openThePhatCommand;
			}
		}

	}
}



