//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 9/10/2017 7:31:59 PM
namespace Provider
{
    
    /// <summary>
    /// There are no comments for qlbhModel.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CatID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="qlbhModel", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="catID">Initial value of CatID.</param>
        /// <param name="catName">Initial value of CatName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Category CreateCategory(int catID, string catName)
        {
            Category category = new Category();
            category.CatID = catID;
            category.CatName = catName;
            return category;
        }
        /// <summary>
        /// There are no comments for property CatID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CatID
        {
            get
            {
                return this._CatID;
            }
            set
            {
                this.OnCatIDChanging(value);
                this.ReportPropertyChanging("CatID");
                this._CatID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CatID");
                this.OnCatIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CatID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatIDChanged();
        /// <summary>
        /// There are no comments for property CatName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CatName
        {
            get
            {
                return this._CatName;
            }
            set
            {
                this.OnCatNameChanging(value);
                this.ReportPropertyChanging("CatName");
                this._CatName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CatName");
                this.OnCatNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CatName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatNameChanged();
    }
    /// <summary>
    /// There are no comments for qlbhEntities in the schema.
    /// </summary>
    public partial class qlbhEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new qlbhEntities object using the connection string found in the 'qlbhEntities' section of the application configuration file.
        /// </summary>
        public qlbhEntities() : 
                base("name=qlbhEntities", "qlbhEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new qlbhEntities object.
        /// </summary>
        public qlbhEntities(string connectionString) : 
                base(connectionString, "qlbhEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new qlbhEntities object.
        /// </summary>
        public qlbhEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "qlbhEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Category> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<Category>("[Categories]");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Category> _Categories;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    }
}
