//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1642021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REST_ATMEntities : DbContext
    {
        public REST_ATMEntities()
            : base("name=REST_ATMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<NganHang> NganHangs { get; set; }
        public virtual DbSet<The> Thes { get; set; }
    }
}
